# -*- coding: utf-8 -*-
"""Tema 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VFv62drQM_soucjnQOdVTDnvK93ZBy-z
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# 1. Preparación de dataset
datos = [
    ("¿Cuándo inicia el semestre?", "inicio_semestre"),
    ("¿Qué día empiezan las clases?", "inicio_semestre"),
    ("¿Cuándo comienza el periodo escolar?", "inicio_semestre"),

    ("¿Dónde puedo consultar mis calificaciones?", "consulta_calificaciones"),
    ("¿Dónde veo mis notas?", "consulta_calificaciones"),
    ("¿Cómo reviso mis calificaciones?", "consulta_calificaciones"),

    ("¿Cómo solicito una constancia de estudios?", "solicitud_constancia"),
    ("¿Dónde tramito una constancia?", "solicitud_constancia"),
    ("¿Cómo pido un comprobante de estudios?", "solicitud_constancia"),

    ("¿Dónde descargo mi horario?", "consulta_horario"),
    ("¿Cómo veo mi horario de clases?", "consulta_horario"),
    ("¿En qué portal está mi horario?", "consulta_horario"),
]

# 2. Vectorización
textos = [x[0] for x in datos]
etiquetas = [x[1] for x in datos]

# 3. Entrenamiento
vectorizador = TfidfVectorizer()
X = vectorizador.fit_transform(textos)

# 4. Predicción
modelo = LogisticRegression()
modelo.fit(X, etiquetas)

# 5. Base de respuestas
respuestas = {
    "inicio_semestre": "El semestre inicia el 15 de agosto. Puedes consultar el calendario oficial en el portal institucional.",
    "consulta_calificaciones": "Puedes consultar tus calificaciones en el portal académico institucional con tu matrícula y contraseña.",
    "solicitud_constancia": "La constancia de estudios se solicita en la sección de trámites escolares del portal universitario.",
    "consulta_horario": "Tu horario está disponible en el sistema de servicios escolares, en la sección 'Horario de clases'."
}

# 6. Función para responder
def responder(pregunta_usuario):
    X_usuario = vectorizador.transform([pregunta_usuario])
    intencion = modelo.predict(X_usuario)[0]
    return intencion, respuestas[intencion]

# 7. Prueba
pregunta = "¿Dónde puedo ver mis notas del semestre?"
intencion_detectada, respuesta = responder(pregunta)

print("Pregunta:", pregunta)
print("Intención detectada:", intencion_detectada)
print("Respuesta:", respuesta)