# -*- coding: utf-8 -*-
"""Tema 21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11aBkiWjPKZFwoZHF5x9dwd9W9BnI-t_Z

**Generación de texto a partir de imágenes**
"""

from transformers import BlipProcessor, BlipForConditionalGeneration
from PIL import Image
import torch
import os

modelo = "Salesforce/blip-image-captioning-base"

processor = BlipProcessor.from_pretrained(modelo)
model = BlipForConditionalGeneration.from_pretrained(modelo)

ruta_imagen = "/content/perrito.jpg"

if not os.path.exists(ruta_imagen):
    print(f"No se encontró la imagen: {ruta_imagen}")
else:
    imagen = Image.open(ruta_imagen).convert("RGB")

    # Captioning sin prompt
    inputs = processor(images=imagen, return_tensors="pt")

    with torch.no_grad():
        output = model.generate(**inputs, max_new_tokens=50)

    descripcion = processor.decode(output[0], skip_special_tokens=True)

    print("Descripción generada:")
    print(descripcion)