# -*- coding: utf-8 -*-
"""Tema 18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h8r1clU4368pHxma8Z5-125EMREGj1qJ

**Implementación básica con Hugging Face y PyTorch**
"""

from transformers import CLIPProcessor, CLIPModel
from PIL import Image

model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

image = Image.open("imagen.jpg")

texts = ["un perro", "un coche", "una persona"]

inputs = processor(text=texts, images=image, return_tensors="pt", padding=True)

outputs = model(**inputs)

probs = outputs.logits_per_image.softmax(dim=1)

print(probs)