# -*- coding: utf-8 -*-
"""Tema 15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gwdyHrDKdYqOO-7tXwwv8Cow3nc_98uT

**Instalación de librerias**
"""

pip install datasets pandas Pillow matplotlib  mplcursors scikit-learn python-doctr
pip install torch torchvision --index-url https://download.pytorch.org/whl/cu121

"""**Importación, estructuración en DataFrame y exploración visual del documento de prueba**"""

from datasets import load_dataset
import matplotlib.pyplot as plt
import pandas as pd
print("Descargando dataset...")
dataset = load_dataset("mauroibz/facturas-argentinas")
df = pd.DataFrame(dataset['train'])
indice = 0
ejemplo_fila = df.iloc[indice]
imagen = ejemplo_fila['image']
plt.figure(figsize=(10, 8))
plt.imshow(imagen)
plt.axis('off')
plt.show()

"""**Configuración del hardware de procesamiento, ejecución del modelo OCR y extracción de texto**"""

import ssl
# 1. Desactivar la verificación de certificados SSL (Solución al SSLCertVerificationError)
ssl._create_default_https_context = ssl._create_unverified_context
import torch
from doctr.models import ocr_predictor
import numpy as np
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Usando dispositivo: {device}")
model = ocr_predictor(pretrained=True).to(device)
img_pil = df.iloc[0]['image'].convert("RGB")
img_array = np.array(img_pil)
result = model([img_array])
output = result.export()
for page in output['pages']:
    for block in page['blocks']:
        for line in block['lines']:
            if line['geometry'][0][0] < 0.2:
                line_text = " ".join([w['value'] for w in line['words']])
                print(f"Texto: {line_text}")

result.show()

"""**Jerarquía geométrica del documento y estructuración del texto extraído**"""

import pandas as pd
page = result.export()['pages'][0]
line_data = []
for block in page['blocks']:
    for line in block['lines']:
        texto = " ".join([w['value'] for w in line['words']])
        line_data.append({
            'linea': texto,
            'coordenada': line['geometry']
        })
df_final = pd.DataFrame(line_data)

"""**Procesamiento de coordenadas geométricas y ordenamiento espacial**"""

import ast
def extraer_xmin(coord):
    if isinstance(coord, str): coord = ast.literal_eval(coord)
    return coord[0][0]

def extraer_ymin(coord):
    if isinstance(coord, str): coord = ast.literal_eval(coord)
    return coord[0][1]

def extraer_ymax(coord):
    if isinstance(coord, str): coord = ast.literal_eval(coord)
    return coord[1][1]

df = df_final.copy()
df['xmin'] = df['coordenada'].apply(extraer_xmin)
df['ymin'] = df['coordenada'].apply(extraer_ymin)
df['ymax'] = df['coordenada'].apply(extraer_ymax)
df['y_center'] = (df['ymin'] + df['ymax']) / 2
df['linea_y'] = df['y_center'].round(2)
df = df.sort_values(by=['linea_y', 'xmin'])
lineas_texto = []
for y_val, linea_group in df.groupby('linea_y', sort=False):
    texto_linea = ' \t '.join(linea_group['linea'].astype(str).str.strip())
    lineas_texto.append(texto_linea)
raw_text = "\n".join(lineas_texto)
print(raw_text)

"""**Diseño del prompt**"""

prompt = f"""
Actúa como un experto en procesamiento de documentos contables y extracción de datos (OCR Data Extraction).
Tu objetivo es analizar el texto de una factura y extraer exclusivamente la información del emisor y el monto total.

### TEXTO DE LA FACTURA:
{raw_text}

### INSTRUCCIONES DE EXTRACCIÓN:
1. Identifica el 'Emisor' buscando el nombre legal o la 'Razón Social' que encabeza el documento.
2. Identifica el 'Total' buscando el importe final después de impuestos (IVA) y otros cargos.
3. Asegúrate de que el número del total mantenga su formato original (puntos de miles y comas decimales).

### REGLAS CRÍTICAS:
- Devuelve la información ÚNICAMENTE en formato JSON.
- No incluyas explicaciones, introducciones ni comentarios adicionales.
- Si no encuentras un valor, devuelve "null".

### FORMATO DE SALIDA REQUERIDO:
{{
  "emisor": "NOMBRE_O_RAZON_SOCIAL",
  "total": "MONTO_CON_SIMBOLO_Y_DECIMALES"
}}
"""

"""**Conexión con la API local de Ollama**"""

import requests
import json
url = "http://localhost:11434/api/generate"
payload = {
    "model": "qwen3.5:latest",
    "prompt": prompt,
    "stream": False,
}
try:
    response = requests.post(url, json=payload)
    response.raise_for_status()
    result = response.json()
    data_extraida = json.loads(result['response'])

    print("--- Datos Extraídos ---")
    print(f"Emisor: {data_extraida.get('emisor')}")
    print(f"Total:  {data_extraida.get('total')}")
except Exception as e:
    print(f"Error en la petición: {e}")