# -*- coding: utf-8 -*-
"""Tema 12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10biCYjgRNDqaBrLlox8t1CNMDbqMmKdD

**CNN básica entrenada desde cero**
"""

import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

# 1. Cargar dataset CIFAR-10
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

# 2. Normalizar imágenes
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

# 3. Nombres de las clases
class_names = ['avión', 'automóvil', 'pájaro', 'gato', 'venado',
               'perro', 'rana', 'caballo', 'barco', 'camión']

# 4. Definir CNN básica
cnn_model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(32,32,3)),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(128, (3,3), activation='relu'),
    layers.Flatten(),

    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(10, activation='softmax')
])

# 5. Compilar modelo
cnn_model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

# 6. Entrenar
history_cnn = cnn_model.fit(
    x_train, y_train,
    epochs=15,
    batch_size=64,
    validation_split=0.2
)

# 7. Evaluar
test_loss, test_acc = cnn_model.evaluate(x_test, y_test)
print("Accuracy CNN básica:", test_acc)

"""Transfer learning con EfficientNetB0"""

# 1. Redimensionar imágenes a 224x224
x_train_resized = tf.image.resize(x_train, (224, 224))
x_test_resized = tf.image.resize(x_test, (224, 224))

# 2. Modelo base preentrenado
base_model = tf.keras.applications.EfficientNetB0(
    include_top=False,
    weights='imagenet',
    input_shape=(224, 224, 3)
)

# 3. Congelar extractor de características
base_model.trainable = False

# 4. Construir modelo final
tl_model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dropout(0.3),
    layers.Dense(10, activation='softmax')
])

# 5. Compilar
tl_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
                 loss='sparse_categorical_crossentropy',
                 metrics=['accuracy'])

# 6. Entrenar
history_tl = tl_model.fit(
    x_train_resized, y_train,
    epochs=8,
    batch_size=32,
    validation_split=0.2
)

# 7. Evaluar
test_loss_tl, test_acc_tl = tl_model.evaluate(x_test_resized, y_test)
print("Accuracy Transfer Learning:", test_acc_tl)

"""**Fine-tuning parcial**"""

# Descongelar las últimas capas del modelo base
base_model.trainable = True

for layer in base_model.layers[:-20]:
    layer.trainable = False

# Recompilar con learning rate pequeño
tl_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
                 loss='sparse_categorical_crossentropy',
                 metrics=['accuracy'])

# Reentrenar
history_ft = tl_model.fit(
    x_train_resized, y_train,
    epochs=5,
    batch_size=32,
    validation_split=0.2
)

# Evaluación final
test_loss_ft, test_acc_ft = tl_model.evaluate(x_test_resized, y_test)
print("Accuracy Fine-Tuning:", test_acc_ft)

"""**Curvas de entrenamiento**"""

def plot_history(history, title):
    plt.figure(figsize=(10,4))

    plt.subplot(1,2,1)
    plt.plot(history.history['accuracy'], label='Entrenamiento')
    plt.plot(history.history['val_accuracy'], label='Validación')
    plt.title(f'Accuracy - {title}')
    plt.xlabel('Época')
    plt.ylabel('Accuracy')
    plt.legend()

    plt.subplot(1,2,2)
    plt.plot(history.history['loss'], label='Entrenamiento')
    plt.plot(history.history['val_loss'], label='Validación')
    plt.title(f'Loss - {title}')
    plt.xlabel('Época')
    plt.ylabel('Loss')
    plt.legend()

    plt.show()

plot_history(history_cnn, "CNN básica")
plot_history(history_tl, "Transfer Learning")

"""**Matriz de confusión y reporte de clasificación**"""

# Predicciones con el modelo final
y_pred = tl_model.predict(x_test_resized)
y_pred_classes = np.argmax(y_pred, axis=1)

# Matriz de confusión
cm = confusion_matrix(y_test, y_pred_classes)

plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel("Predicción")
plt.ylabel("Etiqueta real")
plt.title("Matriz de confusión")
plt.show()

# Reporte de clasificación
print(classification_report(y_test, y_pred_classes, target_names=class_names))