# -*- coding: utf-8 -*-
"""Tema 24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-cEmNV3gU_m_9Yj0x9zs1xSezOaTYhl3

Generación de descripción automática de una imagen
"""

import pandas as pd
from datasets import load_dataset
from transformers import pipeline
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# 1. Cargar un subconjunto ligero del dataset público Flickr8k
dataset = load_dataset("jxie/flickr8k", split="train[:300]")

# 2. Convertir a DataFrame
rows = []
for ex in dataset:
    captions = [ex["caption_0"], ex["caption_1"], ex["caption_2"], ex["caption_3"], ex["caption_4"]]
    rows.append({
        "image": ex["image"],
        "report_text": captions[0]  # usar el primer caption como texto base
    })

df = pd.DataFrame(rows)

# 3. Crear una etiqueta demostrativa para fines didácticos
# Esta etiqueta NO representa una verdad de negocio; solo sirve para mostrar el pipeline completo.
def prioridad_demo(texto: str) -> str:
    t = texto.lower()
    if any(k in t for k in ["dog", "dogs", "running", "jumping", "bike", "street"]):
        return "alta"
    elif any(k in t for k in ["child", "children", "park", "water", "grass"]):
        return "media"
    return "baja"

df["label"] = df["report_text"].apply(prioridad_demo)

# 4. Modelo ligero para generar caption automático de la imagen
captioner = pipeline(
    task="image-to-text",
    model="Salesforce/blip-image-captioning-base",
    device=-1   # usar CPU
)

# Para que la práctica siga siendo ligera, trabajar con una muestra más pequeña
df = df.head(120).copy()

def generar_caption(img):
    salida = captioner(img)
    return salida[0]["generated_text"].strip()

df["image_caption"] = df["image"].apply(generar_caption)

# 5. Fusionar texto original + caption generado
df["fused_text"] = (
    "texto_original: " + df["report_text"].astype(str) +
    " | descripcion_imagen: " + df["image_caption"].astype(str)
)

# 6. Separar entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(
    df["fused_text"],
    df["label"],
    test_size=0.30,
    random_state=42,
    stratify=df["label"]
)

# 7. Vectorizar el texto fusionado
vectorizer = TfidfVectorizer(ngram_range=(1, 2), min_df=1)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# 8. Entrenar clasificador
clf = LogisticRegression(max_iter=2000, class_weight="balanced")
clf.fit(X_train_vec, y_train)

# 9. Predecir
y_pred = clf.predict(X_test_vec)

# 10. Evaluar
print(classification_report(y_test, y_pred))

labels_sorted = sorted(df["label"].unique())
cm = confusion_matrix(y_test, y_pred, labels=labels_sorted)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels_sorted)
disp.plot(xticks_rotation=45)
plt.tight_layout()
plt.show()

# 11. Mostrar algunos resultados
resultados = pd.DataFrame({
    "texto_fusionado": X_test.values,
    "label_real": y_test.values,
    "label_pred": y_pred
})
print(resultados.head(10))

"""**Evaluación del prototipo**"""

from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Reporte de clasificación
print(classification_report(y_test, y_pred))

# Matriz de confusión
labels_sorted = sorted(df["label"].unique())
cm = confusion_matrix(y_test, y_pred, labels=labels_sorted)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=labels_sorted
)
disp.plot(xticks_rotation=45)
plt.tight_layout()
plt.show()