# -*- coding: utf-8 -*-
"""Tema 16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ftd_KI6FrujgdbqCJPyfTsxbF7lwrm8i

**Servicio de inferencia mediante API REST**
"""

from flask import Flask, request, jsonify
import numpy as np
import cv2
import requests
app = Flask(__name__)
# URL del servicio de inferencia
TF_SERVING_URL = "http://localhost:8501/v1/models/modelo:predict"

def preprocess_image(image):
    image = cv2.resize(image, (224, 224))
    image = image.astype("float32") / 255.0
    image = np.expand_dims(image, axis=0)
    return image.tolist()
@app.route("/predict", methods=["POST"])
def predict():
    try:
        if "file" not in request.files:
            return jsonify({"error": "No se envió ninguna imagen"}), 400
        file = request.files["file"]
        image_bytes = np.frombuffer(file.read(), np.uint8)
        image = cv2.imdecode(image_bytes, cv2.IMREAD_COLOR)
        if image is None:
            return jsonify({"error": "La imagen no pudo procesarse"}), 400
        processed = preprocess_image(image)
        response = requests.post(
            TF_SERVING_URL,
            json={"instances": processed},
            timeout=10
        )
        response.raise_for_status()
        predictions = response.json()
        return jsonify(predictions), 200

    except requests.exceptions.RequestException as e:
        return jsonify({"error": "No fue posible conectar con el servicio de inferencia",
                        "detalle": str(e)}), 502
    except Exception as e:
        return jsonify({"error": "Error interno del servidor",
                        "detalle": str(e)}), 500
if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)