# -*- coding: utf-8 -*-
"""Tema 13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jwQyc1mNMAQdgNr78n3zc92SkUV4p7Vh

**Detección y preprocesamiento facial**
"""

#pip install mtcnn[tensorflow]
#pip install opencv-python
# Importar librerías necesarias
import cv2
from mtcnn import MTCNN  # Algoritmo popular para detección de rostros

# Cargar el detector
detector = MTCNN()

def detectar_rostro(ruta_imagen):
    # Cargar la imagen visual
    img = cv2.cvtColor(cv2.imread(ruta_imagen), cv2.COLOR_BGR2RGB)

    # ETAPA 1: DETECCIÓN
    # El algoritmo escanea la imagen buscando patrones geométricos (ojos, nariz)
    # Resultados: Coordenadas del cuadro delimitador (bounding box)
    resultados = detector.detect_faces(img)

    if resultados:
        x, y, ancho, alto = resultados[0]['box']
        # Recortar solo la cara (eliminamos el fondo/ruido)
        cara = img[y:y+alto, x:x+ancho]
        # Redimensionar al tamaño que requiere la red neuronal (ej. 160x160 px)
        cara_procesada = cv2.resize(cara, (160, 160))
        return cara_procesada, img, x, y, ancho, alto
    else:
        return None, img, x, y, ancho, alto

"""**Detección de rostros (bounding box) y recortes (crops)**"""

import matplotlib.pyplot as plt
archivos = ["foto_pasaporte.png", "foto_selfie.png"]
titulos_filas = ["Selfie", "Documento"]

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

for i, archivo in enumerate(archivos):
    # Obtener datos de tu función
    rostro, img_orig, x, y, w, h = detectar_rostro(archivo)

    if rostro is not None:
        # --- A. IMAGEN CON RECTÁNGULO (Contexto) ---
        img_con_box = img_orig.copy()
        # Dibujar rectángulo VERDE
        cv2.rectangle(img_con_box, (x, y), (x+w, y+h), (0, 255, 0), 4)

        axes[i, 0].imshow(img_con_box, aspect='equal') # aspect='equal' evita deformación
        axes[i, 0].set_title(f"{titulos_filas[i]} (Original)", fontsize=10)
        axes[i, 0].axis('off')

        # --- B. RECORTE (Crop) ---
        axes[i, 1].imshow(rostro, aspect='equal')
        axes[i, 1].set_title(f"Recorte detectado ({w}x{h} px)", fontsize=10)

        # Quitamos los ejes pero mantenemos el marco para que se vea el límite del crop
        axes[i, 1].axis('off')

    else:
        axes[i, 0].text(0.5, 0.5, "No detectado", ha='center')
        axes[i, 1].text(0.5, 0.5, "N/A", ha='center')

plt.tight_layout()
plt.show()

"""**Generación de vectores biométricos**"""

#pip install keras-facenet numpy
#pip install pip-system-certs
import numpy as np
from keras_facenet import FaceNet

# 1. Cargar el modelo FaceNet pre-entrenado
# Este modelo ya "sabe" cómo convertir caras en números gracias a un entrenamiento previo masivo
embedder = FaceNet()

def calcular_embedding(rostro_procesado):
    """
    Recibe: Imagen del rostro (160x160 px).
    Devuelve: Vector numérico (Embedding) de 512 dimensiones.
    """
    if rostro_procesado is None:
        return None
    # Preprocesamiento: FaceNet espera un lote (batch) de imágenes
    muestras = np.expand_dims(rostro_procesado, axis=0)

    # CÁLCULO DEL EMBEDDING
    # La red neuronal recorre la imagen y genera el vector de características
    embedding = embedder.embeddings(muestras)

    # Devolvemos solo el primer vector (porque solo pasamos una imagen)
    return embedding[0]

# --- EJECUCIÓN (Usando las salidas del código anterior) ---
rostro_pasaporte, img_orig, x, y, w, h = detectar_rostro("foto_pasaporte.png")
rostro_selfie, img_orig, x, y, w, h = detectar_rostro("foto_selfie.png")
vector_pasaporte = calcular_embedding(rostro_pasaporte)
vector_selfie = calcular_embedding(rostro_selfie)

# Ejemplo de visualización de los datos
print(f"Dimensión del vector: {len(vector_pasaporte)}")
print(f"Primeros 5 valores (Firma Biométrica): {vector_pasaporte[:5]}")

"""**Algoritmo de verificación**"""

from scipy.spatial.distance import cosine

# ==========================================
# ETAPA 3: COMPARACIÓN Y VERIFICACIÓN
# ==========================================

def comparar_embeddings(vector_referencia, vector_prueba, umbral=0.40):
    """
    Compara dos vectores biométricos usando la Distancia Coseno.

    Parámetros:
        vector_referencia: Embedding del pasaporte.
        vector_prueba: Embedding de la selfie.
        umbral (threshold): Límite máximo de diferencia permitida.
                            (0.40 es un estándar común para FaceNet).
    """
    # La distancia coseno mide el ángulo entre dos vectores.
    # Valor cercano a 0: Los vectores son casi idénticos (Misma Persona).
    # Valor cercano a 1: Los vectores son muy diferentes (Personas Distintas).
    distancia = cosine(vector_referencia, vector_prueba)

    # Decisión Lógica
    es_misma_persona = distancia < umbral

    return distancia, es_misma_persona

# --- EJEMPLO DE USO (Continuación del flujo) ---
distancia_calculada, resultado = comparar_embeddings(vector_pasaporte, vector_selfie)

# Visualización del Resultado para el Usuario
print(f"--- REPORTE DE VERIFICACIÓN ---")
print(f"Distancia Biométrica: {distancia_calculada}") # Ejemplo de valor real
print(f"Umbral de Seguridad:  0.40")

if resultado: # Simulación de resultado positivo (resultado == True)
    print("\n[+] ACCESO CONCEDIDO: Identidad Verificada.")
    print("    Las firmas matemáticas coinciden.")
else:
    print("\n[-] ACCESO DENEGADO: Rostros no coinciden.")