"""Small bundled corpora used by VoxCustomer.

`TRAINING_CORPUS` is used to fit the traditional TF-IDF + LogisticRegression
baseline. It is intentionally short, balanced, and customer-support flavored.

`EVAL_CORPUS` is a curated, *hand-labeled* test set used to benchmark the
two models against each other on Page 2. It is deliberately seeded with
sarcasm, negation and mixed-sentiment examples so that the gap between a
bag-of-words model and a contextual transformer becomes visible.

Labels are always one of: 'Negative', 'Neutral', 'Positive'.
"""
from __future__ import annotations

LABELS: tuple[str, ...] = ("Negative", "Neutral", "Positive")


# ── Training set (≈300 examples, support/ecommerce flavor) ───────────────────
TRAINING_CORPUS: list[tuple[str, str]] = [
    # Positive (~100)
    ("Excellent service, the agent solved my problem in minutes.", "Positive"),
    ("Absolutely love this product, works perfectly out of the box.", "Positive"),
    ("Great experience, will buy again from this brand.", "Positive"),
    ("The support team was super helpful and friendly.", "Positive"),
    ("Fast shipping and the packaging was beautiful.", "Positive"),
    ("Best purchase I have made all year, highly recommend.", "Positive"),
    ("Setup was easy and the documentation was clear.", "Positive"),
    ("Customer service responded instantly, very impressed.", "Positive"),
    ("The new firmware update fixed all my issues, thank you.", "Positive"),
    ("Outstanding build quality and excellent battery life.", "Positive"),
    ("Refund was processed quickly with no hassle at all.", "Positive"),
    ("The agent went above and beyond to help me.", "Positive"),
    ("Smooth onboarding, intuitive interface, very happy.", "Positive"),
    ("This headset sounds amazing, totally worth the price.", "Positive"),
    ("Order arrived early and in perfect condition.", "Positive"),
    ("Their chatbot actually understood my question, wow.", "Positive"),
    ("My issue was resolved on the first call, brilliant.", "Positive"),
    ("Product works as advertised, no complaints whatsoever.", "Positive"),
    ("Returning was painless and the credit appeared the same day.", "Positive"),
    ("Their mobile app is a pleasure to use.", "Positive"),
    ("The camera quality blew me away.", "Positive"),
    ("Super reliable, I have had no problems in six months.", "Positive"),
    ("The replacement arrived next day, fantastic service.", "Positive"),
    ("Easy to install, easy to use, easy to love.", "Positive"),
    ("Customer support listened and actually fixed the bug.", "Positive"),
    ("My family loves the new console, great holiday gift.", "Positive"),
    ("Crystal clear video calls, very satisfied.", "Positive"),
    ("Battery lasts forever, exactly what I needed.", "Positive"),
    ("Knowledge base article solved my problem in two minutes.", "Positive"),
    ("Excellent value for money, exceeded my expectations.", "Positive"),
    ("Best laptop I have ever owned, blazing fast.", "Positive"),
    ("Loving the new design, feels premium in the hand.", "Positive"),
    ("Setup wizard made the whole process effortless.", "Positive"),
    ("Got a thoughtful follow-up email, nice touch.", "Positive"),
    ("Their warranty replacement was generous and quick.", "Positive"),
    ("Audio quality is rich and balanced, very pleased.", "Positive"),
    ("The interface is sleek and responsive.", "Positive"),
    ("Bug fix shipped within a day of my report, impressive.", "Positive"),
    ("Highly recommend, customer for life.", "Positive"),
    ("Fantastic product and even better customer care.", "Positive"),
    ("The new dashboard saved me hours of work this week.", "Positive"),
    ("Their tech support is genuinely world class.", "Positive"),
    ("Smooth checkout, fast delivery, happy customer.", "Positive"),
    ("Great keyboard, the tactile feedback is perfect.", "Positive"),
    ("Five stars, would buy again without hesitation.", "Positive"),
    ("My drone flies beautifully and the app is intuitive.", "Positive"),
    ("Speaker sound is rich, deep, and crystal clear.", "Positive"),
    ("Service rep was empathetic and incredibly competent.", "Positive"),
    ("Got an upgrade for free, absolutely delighted.", "Positive"),
    ("The display is gorgeous, colors are vibrant.", "Positive"),
    ("Refund credited within minutes, very professional.", "Positive"),
    ("Setup took two minutes and it just works.", "Positive"),
    ("Wireless connection is rock solid in every room.", "Positive"),
    ("Onboarding emails were genuinely useful.", "Positive"),
    ("Replacement unit works perfectly, very grateful.", "Positive"),
    ("Documentation is the best I have seen in years.", "Positive"),
    ("Battery doubled compared to my previous device.", "Positive"),
    ("Fitness tracker is accurate and the app is fun.", "Positive"),
    ("Smart speaker understands me even with background noise.", "Positive"),
    ("The technician was punctual and very respectful.", "Positive"),
    ("Coffee maker brews exactly as I configured it.", "Positive"),
    ("Their loyalty discount made my day.", "Positive"),
    ("Vacuum is quiet and cleans deeply, very satisfied.", "Positive"),
    ("Best printer setup experience I have ever had.", "Positive"),
    ("Software update was seamless, no downtime.", "Positive"),
    ("Live chat agent fixed the bug in real time.", "Positive"),
    ("Order tracking is accurate and reassuring.", "Positive"),
    ("They honored the price match instantly.", "Positive"),
    ("Microphone picks up my voice perfectly during meetings.", "Positive"),
    ("Mouse glides smoothly and the buttons feel premium.", "Positive"),
    ("Headphones are comfortable even after long sessions.", "Positive"),
    ("Console runs games at perfect frame rate, love it.", "Positive"),
    ("Camera autofocus is fast and reliable.", "Positive"),
    ("Tablet display is sharp and the touch response is great.", "Positive"),
    ("They reshipped the missing item the same day, brilliant.", "Positive"),
    ("Beautiful design and excellent ergonomics.", "Positive"),
    ("My ticket was resolved before I even followed up.", "Positive"),
    ("They proactively credited my account, what a surprise.", "Positive"),
    ("The integration just worked out of the box.", "Positive"),
    ("Great onboarding, great product, great team.", "Positive"),
    ("Solid performance, exactly what I needed for work.", "Positive"),
    ("Easy returns, no questions asked, very fair.", "Positive"),
    ("Stable, fast, beautiful — three reasons I am sticking around.", "Positive"),
    ("Their API documentation is a thing of beauty.", "Positive"),
    ("Real-time sync is flawless across all my devices.", "Positive"),
    ("The escalation team handled my case with care.", "Positive"),
    ("Custom build looks stunning and runs cool.", "Positive"),
    ("I trust this brand more after this support call.", "Positive"),
    ("They went the extra mile, I am genuinely happy.", "Positive"),
    ("Slick interface and powerful features.", "Positive"),
    ("New release fixed every annoyance I had, perfect.", "Positive"),
    ("Customer success rep gave me actually useful advice.", "Positive"),
    ("Backup feature saved my project, life saver.", "Positive"),
    ("Their team responded on a Sunday, that is service.", "Positive"),
    ("Excellent, the product exceeded my expectations.", "Positive"),
    ("Smooth, intuitive, beautiful — couldn't ask for more.", "Positive"),
    ("My productivity went up the moment I started using this.", "Positive"),
    ("Bug bounty was respected and paid out quickly, thank you.", "Positive"),
    ("The latest version is genuinely a delight to use.", "Positive"),
    ("Support call took two minutes and solved everything.", "Positive"),
    ("Speaker integrates flawlessly with my home setup.", "Positive"),

    # Negative (~100)
    ("Terrible experience, my package never arrived.", "Negative"),
    ("The product broke after two days, complete waste of money.", "Negative"),
    ("Customer service was rude and unhelpful.", "Negative"),
    ("I waited two hours on hold and got disconnected.", "Negative"),
    ("This device crashes every single day, infuriating.", "Negative"),
    ("Worst purchase I have ever made, do not buy.", "Negative"),
    ("Refund still not processed after three weeks.", "Negative"),
    ("The agent kept transferring me, nothing got solved.", "Negative"),
    ("Battery dies in two hours, completely useless.", "Negative"),
    ("App is buggy, slow, and constantly crashes.", "Negative"),
    ("My screen cracked the first day, terrible quality.", "Negative"),
    ("The chatbot is useless and gives wrong information.", "Negative"),
    ("Order was wrong, support refuses to help.", "Negative"),
    ("Charging cable melted, this is a safety hazard.", "Negative"),
    ("They lost my package and blamed the courier.", "Negative"),
    ("The replacement is just as broken as the original.", "Negative"),
    ("Update bricked my device, support unresponsive.", "Negative"),
    ("Documentation is misleading and out of date.", "Negative"),
    ("Camera quality is awful, photos come out blurry.", "Negative"),
    ("Shipping was late and the box was damaged.", "Negative"),
    ("Their support email never replies, just silence.", "Negative"),
    ("Software is unstable and randomly logs me out.", "Negative"),
    ("Keyboard keys started failing within a month.", "Negative"),
    ("Speaker hisses constantly, audio quality is terrible.", "Negative"),
    ("I was charged twice and nobody will refund me.", "Negative"),
    ("Setup instructions are confusing and incomplete.", "Negative"),
    ("Microphone does not work, video calls are impossible.", "Negative"),
    ("Vacuum stopped working after one week.", "Negative"),
    ("Console overheats during normal play.", "Negative"),
    ("Their billing system charged me for items I returned.", "Negative"),
    ("Tablet screen flickers, hardware defect.", "Negative"),
    ("Mouse double-clicks on its own, super annoying.", "Negative"),
    ("Headphones broke at the hinge, cheap construction.", "Negative"),
    ("Wireless drops every five minutes, unusable.", "Negative"),
    ("Printer jams constantly and the warranty was denied.", "Negative"),
    ("They closed my ticket without solving the problem.", "Negative"),
    ("The escalation team is just as unhelpful as level one.", "Negative"),
    ("Smart speaker keeps mishearing simple commands.", "Negative"),
    ("Fitness tracker readings are wildly inaccurate.", "Negative"),
    ("Drone crashed on first flight, defective gyroscope.", "Negative"),
    ("Coffee machine leaks water everywhere.", "Negative"),
    ("The agent hung up on me mid-conversation.", "Negative"),
    ("They promised a callback that never came.", "Negative"),
    ("The integration is broken and support shrugs.", "Negative"),
    ("Latest update deleted all my saved settings.", "Negative"),
    ("Camera lens arrived scratched, clearly used.", "Negative"),
    ("App refuses to connect to the device, total fail.", "Negative"),
    ("They sent the wrong product and refuse to fix it.", "Negative"),
    ("Hardware defective out of the box, very disappointing.", "Negative"),
    ("Support agent insulted my intelligence on chat.", "Negative"),
    ("Their cancellation flow is intentionally hostile.", "Negative"),
    ("The product description was completely misleading.", "Negative"),
    ("Software corrupted my data, hours of work lost.", "Negative"),
    ("Battery swelled and burst, dangerous defect.", "Negative"),
    ("Service center kept my laptop for a month with no update.", "Negative"),
    ("The new design is uglier and harder to use.", "Negative"),
    ("Speaker arrived crushed, packaging was inadequate.", "Negative"),
    ("They denied my warranty claim with no explanation.", "Negative"),
    ("Touchscreen is unresponsive, manufacturing defect.", "Negative"),
    ("Replacement charger never arrived, dropped the ball.", "Negative"),
    ("My account got locked and nobody can unlock it.", "Negative"),
    ("The agent was condescending and dismissive.", "Negative"),
    ("Their refund policy is a scam, avoid this company.", "Negative"),
    ("Smart bulb keeps disconnecting from the hub.", "Negative"),
    ("Game freezes on every loading screen, unplayable.", "Negative"),
    ("Their app drains battery overnight, useless.", "Negative"),
    ("Customer rep argued with me instead of helping.", "Negative"),
    ("Manual is in three different fonts and makes no sense.", "Negative"),
    ("The product is dead on arrival, big waste of time.", "Negative"),
    ("Wireless mouse stops working after thirty seconds.", "Negative"),
    ("Their API constantly returns 500 errors.", "Negative"),
    ("Dashboard is buggy and the numbers contradict each other.", "Negative"),
    ("Their pricing page lies about the actual cost.", "Negative"),
    ("They charged me a fee for cancelling my own subscription.", "Negative"),
    ("This is the worst onboarding I have ever seen.", "Negative"),
    ("Knowledge base articles are outdated and useless.", "Negative"),
    ("Phone overheats while charging, that is dangerous.", "Negative"),
    ("Battery indicator is wrong, device dies suddenly.", "Negative"),
    ("Order has been stuck in 'processing' for ten days.", "Negative"),
    ("Their support thinks the problem is my fault.", "Negative"),
    ("Chat session timed out three times in a row.", "Negative"),
    ("New version removed the feature I relied on.", "Negative"),
    ("Pre-installed bloatware is impossible to remove.", "Negative"),
    ("Their refund flow requires calling three departments.", "Negative"),
    ("Console makes a loud buzzing noise constantly.", "Negative"),
    ("Charging port is loose, cable falls out on its own.", "Negative"),
    ("Their loyalty program just stopped working overnight.", "Negative"),
    ("The promised feature does not exist in the product.", "Negative"),
    ("Watch stopped tracking after a software update.", "Negative"),
    ("This is the third defective unit they have sent me.", "Negative"),
    ("Their server keeps going down during peak hours.", "Negative"),
    ("My data was leaked and they offered no explanation.", "Negative"),
    ("Setup process kept failing without an error message.", "Negative"),
    ("Speaker has a permanent crackling sound, defective.", "Negative"),
    ("Their advertised return window is a lie.", "Negative"),
    ("Game crashes if you press start, completely broken.", "Negative"),
    ("Their warranty form is intentionally impossible to submit.", "Negative"),
    ("Camera focus hunts constantly, ruining every shot.", "Negative"),
    ("Bluetooth pairing fails every single time.", "Negative"),
    ("Customer support is a chatbot pretending to be human.", "Negative"),
    ("Their delivery driver dumped the box in a puddle.", "Negative"),

    # Neutral (~100)
    ("I would like to update my shipping address.", "Neutral"),
    ("Please confirm whether my order has shipped.", "Neutral"),
    ("Can you tell me when my replacement will arrive?", "Neutral"),
    ("I need help resetting my account password.", "Neutral"),
    ("Looking for the manual for model X200.", "Neutral"),
    ("Is the new firmware compatible with the older device?", "Neutral"),
    ("What is your return policy for opened items?", "Neutral"),
    ("How do I add a second user to my plan?", "Neutral"),
    ("Where can I find the warranty information?", "Neutral"),
    ("Please reschedule my technician appointment for Friday.", "Neutral"),
    ("I would like to upgrade my subscription tier.", "Neutral"),
    ("Is the product currently in stock at your warehouse?", "Neutral"),
    ("How do I export my data to a CSV file?", "Neutral"),
    ("Please send me a copy of the invoice.", "Neutral"),
    ("My tracking number is not showing any updates.", "Neutral"),
    ("Do you ship internationally to Mexico?", "Neutral"),
    ("Can I pay in monthly installments?", "Neutral"),
    ("Please move my account to the new billing system.", "Neutral"),
    ("What are the dimensions of the package?", "Neutral"),
    ("I am inquiring about bulk pricing for my company.", "Neutral"),
    ("Can you confirm receipt of my returned item?", "Neutral"),
    ("Is there a student discount available?", "Neutral"),
    ("How do I change the language of the interface?", "Neutral"),
    ("Please add my colleague as an admin on the account.", "Neutral"),
    ("Looking for the system requirements documentation.", "Neutral"),
    ("Can you walk me through the migration steps?", "Neutral"),
    ("What is the difference between the Pro and Plus plans?", "Neutral"),
    ("My delivery is scheduled for Tuesday, please confirm.", "Neutral"),
    ("I would like to know the integration options.", "Neutral"),
    ("Does the product support two-factor authentication?", "Neutral"),
    ("Where can I download the latest driver?", "Neutral"),
    ("Please confirm whether the promo code is still valid.", "Neutral"),
    ("What time zone do your support hours follow?", "Neutral"),
    ("How do I generate an API token?", "Neutral"),
    ("Could you point me to the changelog?", "Neutral"),
    ("Is there a known incident affecting the dashboard today?", "Neutral"),
    ("I want to enable email notifications for new tickets.", "Neutral"),
    ("Please tell me whether the bug I reported has a fix.", "Neutral"),
    ("Where do I view my purchase history?", "Neutral"),
    ("I would like to consolidate two accounts into one.", "Neutral"),
    ("Can you explain how the trial period works?", "Neutral"),
    ("Is there a way to schedule automatic backups?", "Neutral"),
    ("Please update my contact phone number.", "Neutral"),
    ("What payment methods do you accept?", "Neutral"),
    ("I am evaluating your product for my team of fifty.", "Neutral"),
    ("Please confirm the SLA for premium support.", "Neutral"),
    ("Do you offer single sign-on with Okta?", "Neutral"),
    ("How is the per-seat price calculated?", "Neutral"),
    ("Can I migrate from the legacy product?", "Neutral"),
    ("What is the maximum number of devices per account?", "Neutral"),
    ("Could you share the security white paper?", "Neutral"),
    ("Please add VAT details to my next invoice.", "Neutral"),
    ("I want to cancel the auto-renewal on my plan.", "Neutral"),
    ("Where do I see the storage used in my account?", "Neutral"),
    ("Is the data center located in Europe?", "Neutral"),
    ("Please move my subscription to annual billing.", "Neutral"),
    ("Can you share an estimate for the next release?", "Neutral"),
    ("How long does technical onboarding usually take?", "Neutral"),
    ("Please send the contract for legal review.", "Neutral"),
    ("Do you provide on-site training?", "Neutral"),
    ("What is the latency between US and EU regions?", "Neutral"),
    ("Please share the data deletion policy.", "Neutral"),
    ("Is the API rate limit per user or per organization?", "Neutral"),
    ("I would like to test the beta channel.", "Neutral"),
    ("What is the recommended hardware for production?", "Neutral"),
    ("Please confirm the activation key on file.", "Neutral"),
    ("Where do I download my historical reports?", "Neutral"),
    ("Can I export my settings to a different account?", "Neutral"),
    ("Please add me to the maintenance window notifications.", "Neutral"),
    ("Is there a separate sandbox environment?", "Neutral"),
    ("What is the difference between standard and priority shipping?", "Neutral"),
    ("Can I schedule a callback for tomorrow afternoon?", "Neutral"),
    ("How do I redeem a gift card on my account?", "Neutral"),
    ("Please tell me which file formats are supported.", "Neutral"),
    ("Could you confirm the warranty start date?", "Neutral"),
    ("I would like to transfer ownership of the device.", "Neutral"),
    ("How do I change my preferred currency?", "Neutral"),
    ("Please clarify the data residency requirements.", "Neutral"),
    ("Where can I find the compliance reports?", "Neutral"),
    ("Can I get the meeting recording from yesterday?", "Neutral"),
    ("What is included in the standard maintenance package?", "Neutral"),
    ("Please share the implementation timeline.", "Neutral"),
    ("How do I link my employer account?", "Neutral"),
    ("Could you check whether my license is active?", "Neutral"),
    ("I want to schedule a product demo.", "Neutral"),
    ("Is the integration with Slack included?", "Neutral"),
    ("Please update the address on my invoice.", "Neutral"),
    ("What is the export quota per month?", "Neutral"),
    ("Could you share the changelog for version 4?", "Neutral"),
    ("Please confirm whether webhooks support retries.", "Neutral"),
    ("How do I pause my subscription temporarily?", "Neutral"),
    ("I would like to schedule a maintenance window.", "Neutral"),
    ("Is multi-region failover available on my plan?", "Neutral"),
    ("Please send me the SOC 2 report.", "Neutral"),
    ("What user roles are available by default?", "Neutral"),
    ("Could you enable beta features on my account?", "Neutral"),
    ("How do I rotate my API key safely?", "Neutral"),
    ("Please confirm the price for ten additional seats.", "Neutral"),
    ("Where do I see active sessions on my account?", "Neutral"),
    ("Please send a quote for fifty units.", "Neutral"),
]


# ── Evaluation set — hand-labeled, with tricky cases ─────────────────────────
EVAL_CORPUS: list[tuple[str, str]] = [
    # Straightforward positives
    ("Amazing service, my issue was solved in five minutes!", "Positive"),
    ("Best laptop I have ever owned, blazing fast.", "Positive"),
    ("Thanks for the quick response, very helpful.", "Positive"),
    ("The replacement arrived ahead of schedule, great job.", "Positive"),
    ("Loving the new design, feels premium.", "Positive"),

    # Straightforward negatives
    ("Worst experience ever, will never buy again.", "Negative"),
    ("My phone broke after one day, refund denied.", "Negative"),
    ("Customer service hung up on me twice today.", "Negative"),
    ("Battery exploded, this is dangerous.", "Negative"),
    ("Their app crashes every time I open it.", "Negative"),

    # Neutral / informational
    ("Can you tell me the status of order #44312?", "Neutral"),
    ("Please update my shipping address to the new one.", "Neutral"),
    ("Where do I download the latest driver?", "Neutral"),
    ("Is the product compatible with iOS 18?", "Neutral"),
    ("What is your weekend support schedule?", "Neutral"),

    # Sarcasm — true label is Negative
    ("Oh great, another update that breaks my workflow. Just what I needed.", "Negative"),
    ("Wow, only three weeks to get a reply. Truly world-class support.", "Negative"),
    ("Love being charged twice for the same item, fantastic experience.", "Negative"),
    ("Yeah, sure, the agent was 'super helpful' — solved nothing in two hours.", "Negative"),
    ("Brilliant. The replacement is just as broken as the original.", "Negative"),
    ("Amazing, my brand new device arrived with a cracked screen. Loving it.", "Negative"),
    ("Fantastic, the refund will arrive in 6-8 weeks. Cannot wait.", "Negative"),
    ("Such great service: hold music for forty minutes and then disconnected.", "Negative"),
    ("I just love when chatbots tell me my issue is 'resolved' without doing anything.", "Negative"),
    ("Wonderful, the warranty conveniently expired yesterday.", "Negative"),

    # Negation — true label flips the polarity of the strong word
    ("The product is not bad, it actually works really well.", "Positive"),
    ("Not what I expected — in a good way, I am pleasantly surprised.", "Positive"),
    ("I cannot complain, the agent was patient and effective.", "Positive"),
    ("This is not the worst service I have had, honestly quite decent.", "Positive"),
    ("Not happy at all with how my ticket was handled.", "Negative"),
    ("I do not love the new design and the bugs are annoying.", "Negative"),
    ("Cannot say I enjoyed waiting two hours for nothing.", "Negative"),
    ("This is not great, the device keeps disconnecting.", "Negative"),
    ("Not impressed, the replacement is also defective.", "Negative"),
    ("I would not recommend this product to anyone.", "Negative"),

    # Mixed sentiment — overall label depends on the dominant clause
    ("Great hardware, but the software is buggy and the support is awful.", "Negative"),
    ("Setup was painful, but once it works the product is wonderful.", "Positive"),
    ("Love the design, hate the price, will keep it anyway.", "Positive"),
    ("Fast shipping, but the box arrived crushed and the screen is cracked.", "Negative"),
    ("Excellent product, terrible billing experience.", "Negative"),
    ("Decent app, the latest update finally made it usable.", "Positive"),
    ("The agent was kind, but they could not actually solve my problem.", "Negative"),
    ("Quality is solid, packaging could be better.", "Positive"),
    ("Slow start, but after onboarding the value is clear.", "Positive"),
    ("Beautiful UI, the API is a nightmare to integrate.", "Negative"),

    # Subtle / context-heavy
    ("Three months in and I am still finding small things to love.", "Positive"),
    ("After the third broken unit, I have given up on this brand.", "Negative"),
    ("The dashboard finally shows the metrics we have been asking for.", "Positive"),
    ("Promised feature is missing again from the release notes.", "Negative"),
    ("Service was acceptable, nothing remarkable either way.", "Neutral"),
    ("Standard delivery, product matches the description.", "Neutral"),
    ("Tech walked me through the steps and everything is working now.", "Positive"),
    ("Charged for premium support but received basic-tier responses.", "Negative"),
    ("Documentation needs work but the chat agent filled the gaps.", "Positive"),
    ("Will reconsider renewing next year if prices keep climbing.", "Negative"),
]
